pipeline { 
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2 --network ci'
        }
    }
    environment {
        DOCKER_HUB = credentials("hyorch-docker-hub")
    }

    tools {
        maven 'Maven3'
    }
    stages { 
        stage('Maven Clean') { 
            steps {       
                sh "mvn clean" 
            }
        }
        stage('Maven Validate') { 
            steps {       
                sh "mvn validate" 
            }
        }
        stage('Maven Compile') { 
            steps {       
                sh "mvn compile" 
            }
        }
        stage('Maven Test') { 
            steps {       
                sh "mvn test" 
            }
        }
        stage('Maven JIB dockerBuild') { 
            steps {       
                sh "mvn compile jib:dockerBuild" 
            }
        }
    }
    post {
        always {
            junit 'target/surefire-reports/*.xml'
        }
    }
}